DDAC_Maersk/Models/Schedule.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace DDAC_Maersk.Models
{
    public class Schedule
    {
        [Key]
        public int ScheduleID { get; set; }

        [Required]
        public string Origin { get; set; }

        [Required]
        public string Destination { get; set; }

        [Required]
        public string DepatureTime { get; set; }

        [Required]
        public string ArrivalTime{ get; set; }
    }
}

DDAC_Maersk/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DDAC_Maersk.Models;


namespace DDAC_Maersk.Controllers
{
    
        public class ScheduleController : Controller
        {
            private ApplicationDbContext _context;

            public ScheduleController()
            {
                _context = new ApplicationDbContext();
            }

            protected override void Dispose(bool disposing)
            {
                _context.Dispose();
            }

            public ActionResult New()
            {
                return View();
            }

            // GET: Schedules
            public ActionResult Index()
            {
                var schedule = _context.Schedules.ToList();

                return View(schedule);
            }

            //public ActionResult Create()
            //{
            //    return View();
            //}

            public ActionResult Create(Schedule schedule)
            {
                _context.Schedules.Add(schedule);

                _context.SaveChanges();


                var newScheduleInDb = _context.Schedules.Find(schedule.ScheduleID);

                return View("Details", newScheduleInDb);
            }

            public ActionResult Edit(int id)
            {
                var schedule = _context.Schedules.SingleOrDefault(s => s.ScheduleID == id);

                if (schedule == null)
                {
                    return HttpNotFound();
                }

                Schedule editSchedule = new Schedule();
                editSchedule.ScheduleID = schedule.ScheduleID;
                editSchedule.Destination = schedule.Destination;
                editSchedule.Origin = schedule.Origin;
                editSchedule.DepatureTime = schedule.DepatureTime;
                editSchedule.ArrivalTime = schedule.ArrivalTime;

                return View(editSchedule);
            }

            public ActionResult Update(Schedule sche)
            {
                var schedule = _context.Schedules.SingleOrDefault(s => s.ScheduleID == sche.ScheduleID);

                schedule.ScheduleID = sche.ScheduleID;
                schedule.Destination = sche.Destination;
                schedule.Origin = sche.Origin;
                schedule.DepatureTime = sche.DepatureTime;
                schedule.ArrivalTime = sche.ArrivalTime;

                _context.SaveChanges();

                var scheList = _context.Schedules.ToList();

                return View("Index", scheList);
            }

            public ActionResult Delete()
            {
                return View();
            }

            public ActionResult Details(int id)
            {
                var schedule = _context.Schedules.Find(id);

                return View(schedule);
            }
        }
    }

DDAC_Maersk/Views/Schedule/Details.cshtml
@model DDAC_Maersk.Models.Schedule

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Schedule</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Origin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Origin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepatureTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepatureTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArrivalTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArrivalTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ScheduleID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DDAC_Maersk/Views/Schedule/Edit.cshtml
@using DDAC_Maersk.Models
@model DDAC_Maersk.Models.Schedule

@{
    ViewBag.Title = "Edit";
}

<h2>View</h2>

@using (Html.BeginForm("Update", "Schedule"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Schedule</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ScheduleID)

        <div class="form-group">
            @Html.LabelFor(model => model.Origin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Origin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Origin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepatureTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepatureTime, new { htmlAttributes = new { id = "datetimepicker6", @class = " input-group date bootstrap-datetimepicker-widget form-control" } })
                @Html.ValidationMessageFor(model => model.DepatureTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArrivalTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArrivalTime, new { htmlAttributes = new { id = "datetimepicker7", @class = " input-group date bootstrap-datetimepicker-widget form-control" } })
                @Html.ValidationMessageFor(model => model.ArrivalTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(function () {
            $('#datetimepicker6').datetimepicker();
            $('#datetimepicker7').datetimepicker({
                useCurrent: false //Important! See issue #1075
            });
            $("#datetimepicker6").on("dp.change", function (e) {
                $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
            });
            $("#datetimepicker7").on("dp.change", function (e) {
                $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
            });
        });
    </script>
}

DDAC_Maersk/Views/Schedule/Index.cshtml
@model IEnumerable<DDAC_Maersk.Models.Schedule>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "New")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Origin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Destination)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepatureTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArrivalTime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Origin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Destination)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DepatureTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ArrivalTime)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ScheduleID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ScheduleID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ScheduleID })
        </td>
    </tr>
}

</table>

DDAC_Maersk/Views/Schedule/New.cshtml
@model DDAC_Maersk.Models.Schedule
@{
    ViewBag.Title = "New";
}

<h2>New Schedule</h2>

@using (Html.BeginForm("Create", "Schedule"))
{
    @Html.ValidationSummary(false, "", new { @class = "text-danger"})

    <div class="form-group">
        @Html.LabelFor(m => m.Origin)
        @Html.TextBoxFor(m => m.Origin, new { @class = "form-control" })
        @*@Html.ValidationMessage()*@
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Destination)
        @Html.TextBoxFor(m => m.Destination, new { @class = "form-control" })

    </div>

    <div class="form-group input-group date bootstrap-datetimepicker-widget">
        @Html.LabelFor(m => m.DepatureTime)
        @Html.TextBoxFor(m => m.DepatureTime, new { id = "datetimepicker6", @class = "form-control" })

    </div>

    <div class="form-group input-group date bootstrap-datetimepicker-widget">
        @Html.LabelFor(m => m.ArrivalTime)
        @Html.TextBoxFor(m => m.ArrivalTime, new { id = "datetimepicker7", @class = "form-control" })
    </div>

    @Html.HiddenFor(m => m.ScheduleID)

    <button type="submit">Submit</button>
}


@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(function () {
            $('#datetimepicker6').datetimepicker();
            $('#datetimepicker7').datetimepicker({
                useCurrent: false //Important! See issue #1075
            });
            $("#datetimepicker6").on("dp.change", function (e) {
                $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
            });
            $("#datetimepicker7").on("dp.change", function (e) {
                $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
            });
        });
    </script>
}